markdown: kramdown
pygments: true
highlighter: pygments
plugins: ./_plugins
paginate: 8
permalink: /:title

safe: false

#站点基础配置
title: 鯨歌
description:
cover: http://footoredorandom.appsp0t.com/list/UtNXJzaL
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: 关于我
    url: /about.html
    icon: icon-lemon
    class: none
  - text: 联系我
    url: /contact.html
    icon: icon-envelope-alt
    class: none
  - text: Github
    url: https://github.com/footoredo
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: footoredo
