encoding: utf-8
markdown: kramdown
#pygments: true
highlighter: pygments
#kramdown:
#  input: GFM
#  auto_ids: true
#  auto_id_prefix: 'id-'
#kramdown:
#  use_coderay: true
#  coderay:
#    coderay_line_numbers: table
#    coderay_css: class

plugins: ./_plugins
paginate: 8
permalink: /:title

safe: false

#站点基础配置
title: 「腹痛症」
description:
cover: https://footoredorandom.sinaapp.com/KQkIceXM
background: https://dn-footoredo.qbox.me/background_52316949_p0_master1200.jpg
feed: /atom.xml
name: 腹痛症
description: footoredo's blog
url: https://footoredo.cat

links:
  - text: Kyeremal
    url: http://www.kyeremal.com
  - text: Naginikaido
    url: http://naginikaido.github.io

#菜单配置
nav:
  - text: 首页
    url: /index.html
    icon: icon-home
    class: home
  - text: 文章归档
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: 视频 
    url: /video.html
    icon: icon-play-circle
    class: none
  - text: 关于我
    url: /about.html
    icon: icon-lemon
    class: none
  - text: 联系我
    url: /contact.html
    icon: icon-envelope-alt
    class: none
  - text: Github
    url: https://github.com/footoredo
    icon: icon-github
    class: none

page:
  - text: 文章分类
    url: /archives.html
    last: true
  - text: 友情链接
    url: /links.html
    last: true
  - text: 关于我
    url: /contact.html
    last: false

author:
  name: footoredo
